language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="9b0dd8d8-bd58-479d-ad8d-b27298fd7e08"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - zhavoronkov52@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
